
pull_request_rules:
  - name: Automatic merge Scala Steward PR
    conditions:
      - author=scala-steward
      - body~=labels:.*semver-patch.*
      - 'status-success=ci/circleci: test'
    actions:
      merge:
        method: merge