version: '3.4'

x-app:
  &default-app
  image: hseeberger/scala-sbt:8u222_1.3.3_2.12.10
  command: sbt examples/run
  working_dir: /app
  user: 1000:1000
  volumes:
    - "./:/app"
    - "~/.ivy2:/home/sbtuser/.ivy2"
    - ~/.cache/coursier:/home/sbtuser/.cache/coursier
  environment:
    - LOG_LEVEL
    - AWS_REGION=us-east-1
  depends_on:
    - sqs
    - s3
    - db
services:
  app:
    << : *default-app
  test:
    << : *default-app
    command: sbt clean coverage test coverageReport
  sqs:
    image: softwaremill/elasticmq
    ports:
      - 9324:9324
  db:
    image: postgres:10
    ports:
      - 5432
  s3:
    image: minio/minio
    environment:
      - MINIO_ACCESS_KEY=x
      - MINIO_SECRET_KEY=x
    ports:
      - 9000
volumes:
  sbt-ivy2-cache:
    external: true
