version: '3.2'

services:
  app:
    image: hseeberger/scala-sbt:8u222_1.3.3_2.12.14
    command: sbt "example/run worker"
    working_dir: /app
    volumes:
      - "./:/app"
      - "sbt-ivy2-cache:/home/sbtuser/.ivy2"
      - sbt-cousier-cache:/home/sbtuser/.cache/coursier
    environment:
      - LOG_LEVEL
      - AWS_REGION=us-east-1
    depends_on:
      - sqs
      - s3
      - db
  sqs:
    image: softwaremill/elasticmq
    volumes:
      - ./elasticmq.conf:/opt/elasticmq.conf
    ports:
      - 9324:9324
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=zhuyu
    ports:
      - 5432
  s3:
    image: minio/minio
    command: server /data
    environment:
      - MINIO_ACCESS_KEY=xxx
      - MINIO_SECRET_KEY=xxxxxxxx
    ports:
      - 9000:9000
volumes:
  sbt-ivy2-cache:
    external: true
  sbt-cousier-cache:
    external: true
