version: '3.4'

x-app:
  &default-app
  image: hseeberger/scala-sbt:8u181_2.12.8_1.2.8
  command: sbt examples/run
  working_dir: /app
  volumes:
    - "./:/app"
    - "sbt-ivy2-cache:/root/.ivy2"
  environment:
    - LOG_LEVEL
    - AWS_REGION=us-east-1
  depends_on:
    - sqs
services:
  app:
    << : *default-app
  test:
    << : *default-app
    command: sbt clean coverage test coverageReport
  sqs:
    image: softwaremill/elasticmq
    ports:
      - 9324:9324
volumes:
  sbt-ivy2-cache:
    external: true
