#!/bin/bash

docker volume create --name=sbt-ivy2-cache
docker volume create --name=sbt-cousier-cache

export AWS_DEFAULT_REGION=us-east-1
echo "--- start service"
docker-compose up -d app

echo "--- create sqs queue"
env AWS_ACCESS_KEY_ID=x AWS_SECRET_ACCESS_KEY=x aws --endpoint-url=http://localhost:9324 sqs create-queue --queue-name "ExampleEvents"

echo "--- create s3 bucket"
env AWS_ACCESS_KEY_ID=xxx AWS_SECRET_ACCESS_KEY=xxxxxxxx aws --endpoint-url=http://localhost:9000 s3api create-bucket --bucket example-bucket

echo "--- drop an event"
env AWS_ACCESS_KEY_ID=x AWS_SECRET_ACCESS_KEY=x aws --endpoint-url=http://localhost:9324 sqs send-message --queue-url "http://localhost:9324/queue/ExampleEvents" --message-body '{"InitPayment": {"id": 123}}'

echo "--- verify"
docker-compose logs -f app | grep -m 1 "FINISHED (=^･ｪ･^=))ﾉ彡☆" | head -n1
docker-compose down