version: 2.1
description: Scala sbt pipeline
orbs:
  sbt: jcouyang/sbt@dev:0.2.0
jobs:
  test:
    machine:
      enabled: true
    steps:
      - checkout
      - run: ./test
workflows:
  version: 2
  test:
    jobs:
      - test
  release:
    jobs:
      - test:
          filters:
            tags:
              only: /^v[0-9.]+.*/
            branches:
              ignore: /.*/
      - sbt/release:
          requires:
            - test
          filters:
            tags:
              only: /^v[0-9.]+.*/
            branches:
              ignore: /.*/
