version: 2.1
description: Scala sbt pipeline
orbs:
  sbt: jcouyang/sbt@dev:0.2.0
executors:
  scala:
    docker:
      - image: circleci/openjdk:8-jdk
workflows:
  version: 2
  test:
    jobs:
      - sbt/test:
          executor: scala
  release:
    jobs:
      - sbt/test:
          executor: scala
          filters:
            tags:
              only: /^v[0-9.]+.*/
            branches:
              ignore: /.*/
      - sbt/release:
          requires:
            - sbt/test
          filters:
            tags:
              only: /^v[0-9.]+.*/
            branches:
              ignore: /.*/
